MERGE ref.variable AS t
USING (VALUES
  (633677, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - ogółem', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'ogółem', N'ogółem'),
  (633678, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - do 40 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'ogółem', N'do 40 m2'),
  (633679, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 40,1 do 60 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'ogółem', N'od 40,1 do 60 m2'),
  (633680, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 60,1 do 80 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'ogółem', N'od 60,1 do 80 m2'),
  (633681, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 80,1 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'ogółem', N'od 80,1 m2'),
  (633682, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - ogółem', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek pierwotny', N'ogółem'),
  (633683, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - do 40 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek pierwotny', N'do 40 m2'),
  (633684, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 40,1 do 60 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek pierwotny', N'od 40,1 do 60 m2'),
  (633685, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 60,1 do 80 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek pierwotny', N'od 60,1 do 80 m2'),
  (633686, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 80,1 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek pierwotny', N'od 80,1 m2'),
  (633687, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - ogółem', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek wtórny', N'ogółem'),
  (633688, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - do 40 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek wtórny', N'do 40 m2'),
  (633689, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 40,1 do 60 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek wtórny', N'od 40,1 do 60 m2'),
  (633690, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 60,1 do 80 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek wtórny', N'od 60,1 do 80 m2'),
  (633691, N'Mediana cen za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 80,1 m2', N'P3787', N'prices', N'median_price_sqm', N'zł', 5, N'rynek wtórny', N'od 80,1 m2'),
  (633692, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - ogółem', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'ogółem', N'ogółem'),
  (633693, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - do 40 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'ogółem', N'do 40 m2'),
  (633694, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 40,1 do 60 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'ogółem', N'od 40,1 do 60 m2'),
  (633695, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 60,1 do 80 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'ogółem', N'od 60,1 do 80 m2'),
  (633696, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 80,1 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'ogółem', N'od 80,1 m2'),
  (633697, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - ogółem', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek pierwotny', N'ogółem'),
  (633698, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - do 40 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek pierwotny', N'do 40 m2'),
  (633699, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 40,1 do 60 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek pierwotny', N'od 40,1 do 60 m2'),
  (633700, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 60,1 do 80 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek pierwotny', N'od 60,1 do 80 m2'),
  (633701, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 80,1 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek pierwotny', N'od 80,1 m2'),
  (633702, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - ogółem', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek wtórny', N'ogółem'),
  (633703, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - do 40 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek wtórny', N'do 40 m2'),
  (633704, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 40,1 do 60 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek wtórny', N'od 40,1 do 60 m2'),
  (633705, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 60,1 do 80 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek wtórny', N'od 60,1 do 80 m2'),
  (633706, N'Średnia cena za 1 m2 lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 80,1 m2', N'P3788', N'prices', N'avg_price_sqm', N'zł', 5, N'rynek wtórny', N'od 80,1 m2'),
  (633617, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - ogółem', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'ogółem', N'ogółem'),
  (633618, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - do 40 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'ogółem', N'do 40 m2'),
  (633619, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 40,1 do 60 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'ogółem', N'od 40,1 do 60 m2'),
  (633620, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 60,1 do 80 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'ogółem', N'od 60,1 do 80 m2'),
  (633621, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 80,1 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'ogółem', N'od 80,1 m2'),
  (633622, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - ogółem', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek pierwotny', N'ogółem'),
  (633623, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - do 40 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek pierwotny', N'do 40 m2'),
  (633624, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 40,1 do 60 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek pierwotny', N'od 40,1 do 60 m2'),
  (633625, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 60,1 do 80 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek pierwotny', N'od 60,1 do 80 m2'),
  (633626, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 80,1 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek pierwotny', N'od 80,1 m2'),
  (633627, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - ogółem', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek wtórny', N'ogółem'),
  (633628, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - do 40 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek wtórny', N'do 40 m2'),
  (633629, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 40,1 do 60 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek wtórny', N'od 40,1 do 60 m2'),
  (633630, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 60,1 do 80 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek wtórny', N'od 60,1 do 80 m2'),
  (633631, N'Liczba lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 80,1 m2', N'P3783', N'transactions', N'dwellings_sold', N'szt.', 5, N'rynek wtórny', N'od 80,1 m2'),
  (633647, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - ogółem', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'ogółem', N'ogółem'),
  (633648, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - do 40 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'ogółem', N'do 40 m2'),
  (633649, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 40,1 do 60 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'ogółem', N'od 40,1 do 60 m2'),
  (633650, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 60,1 do 80 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'ogółem', N'od 60,1 do 80 m2'),
  (633651, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 80,1 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'ogółem', N'od 80,1 m2'),
  (633652, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - ogółem', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek pierwotny', N'ogółem'),
  (633653, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - do 40 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek pierwotny', N'do 40 m2'),
  (633654, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 40,1 do 60 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek pierwotny', N'od 40,1 do 60 m2'),
  (633655, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 60,1 do 80 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek pierwotny', N'od 60,1 do 80 m2'),
  (633656, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 80,1 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek pierwotny', N'od 80,1 m2'),
  (633657, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - ogółem', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek wtórny', N'ogółem'),
  (633658, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - do 40 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek wtórny', N'do 40 m2'),
  (633659, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 40,1 do 60 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek wtórny', N'od 40,1 do 60 m2'),
  (633660, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 60,1 do 80 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek wtórny', N'od 60,1 do 80 m2'),
  (633661, N'Powierzchnia użytkowa lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 80,1 m2', N'P3785', N'transactions', N'floor_area_sold', N'm2', 5, N'rynek wtórny', N'od 80,1 m2'),
  (633662, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - ogółem', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'ogółem', N'ogółem'),
  (633663, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - do 40 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'ogółem', N'do 40 m2'),
  (633664, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 40,1 do 60 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'ogółem', N'od 40,1 do 60 m2'),
  (633665, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 60,1 do 80 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'ogółem', N'od 60,1 do 80 m2'),
  (633666, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - ogółem - od 80,1 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'ogółem', N'od 80,1 m2'),
  (633667, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - ogółem', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek pierwotny', N'ogółem'),
  (633668, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - do 40 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek pierwotny', N'do 40 m2'),
  (633669, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 40,1 do 60 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek pierwotny', N'od 40,1 do 60 m2'),
  (633670, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 60,1 do 80 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek pierwotny', N'od 60,1 do 80 m2'),
  (633671, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek pierwotny - od 80,1 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek pierwotny', N'od 80,1 m2'),
  (633672, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - ogółem', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek wtórny', N'ogółem'),
  (633673, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - do 40 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek wtórny', N'do 40 m2'),
  (633674, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 40,1 do 60 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek wtórny', N'od 40,1 do 60 m2'),
  (633675, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 60,1 do 80 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek wtórny', N'od 60,1 do 80 m2'),
  (633676, N'Średnia cena lokali mieszkalnych sprzedanych w ramach transakcji rynkowych - rynek wtórny - od 80,1 m2', N'P3786', N'prices', N'avg_dwelling_price', N'zł', 5, N'rynek wtórny', N'od 80,1 m2'),
  (64428, N'Przeciętne miesięczne wynagrodzenia brutto - ogółem', N'P2497', N'income', N'avg_gross_salary', N'zł', 5, N'ogółem', NULL),
  (72305, N'Ludność wg grup wieku i płci - ogółem - ogółem', N'P2137', N'demography', N'population', N'osoba', 5, N'ogółem', N'ogółem'),
  (748601, N'Mieszkania oddane do użytkowania - ogółem - mieszkania', N'P3824', N'supply', N'dwellings_completed', N'-', 5, N'ogółem', N'mieszkania'),
  (748603, N'Mieszkania oddane do użytkowania - ogółem - powierzchnia użytkowa mieszkań', N'P3824', N'supply', N'floor_area_completed', N'm2', 5, N'ogółem', N'powierzchnia użytkowa mieszkań'),
  (410600, N'Zasoby mieszkaniowe - wskaźniki - mieszkania na 1000 mieszkańców', N'P2430', N'housing_stock', N'dwellings_per_1000', N'-', 5, N'mieszkania na 1000 mieszkańców', NULL),
  (475703, N'Zasoby mieszkaniowe - wskaźniki - przeciętna liczba osób na 1 mieszkanie', N'P2430', N'housing_stock', N'persons_per_dwelling', N'-', 5, N'przeciętna liczba osób na 1 mieszkanie', NULL),
  (60573, N'Zasoby mieszkaniowe - wskaźniki - przeciętna powierzchnia użytkowa mieszkania na 1 osobę', N'P2430', N'housing_stock', N'floor_area_per_person', N'm2', 5, N'przeciętna powierzchnia użytkowa mieszkania na 1 osobę', NULL)
) AS s (variable_id, name, subject_id, category, measure, unit_of_measure, unit_level, dimension_1, dimension_2)
ON t.variable_id = s.variable_id
WHEN MATCHED THEN UPDATE SET
    t.name = s.name, t.subject_id = s.subject_id, t.category = s.category,
    t.measure = s.measure, t.unit_of_measure = s.unit_of_measure,
    t.unit_level = s.unit_level, t.dimension_1 = s.dimension_1,
    t.dimension_2 = s.dimension_2, t.modified_at = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT
    (variable_id, name, subject_id, category, measure, unit_of_measure, unit_level, dimension_1, dimension_2)
    VALUES (s.variable_id, s.name, s.subject_id, s.category, s.measure,
            s.unit_of_measure, s.unit_level, s.dimension_1, s.dimension_2);
